# Generated by Django 3.2.9 on 2021-11-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
